settings:
  groups: 
    8iVFB: [longdress, soldier, loot, redandblack]
    solid: [soldier, bouquet, stmichael, thaidancer]
    dense: [Facade, CITISUP, House, boxer]
    sparse: [EPFL, Unicorn, shiva, Arco]
  methods:
    - Main
    - G-PCC
    - V-PCC
    - IT-DL-PCC
    - JPEG-Pleno
    - DeepPCC
    - YOGA
plots:
  main_8i:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      - Main
      - G-PCC
      - V-PCC
      - IT-DL-PCC
      - DeepPCC
      - YOGA
  main_jpeg:
    groups: 
      solid: [soldier, bouquet, stmichael, thaidancer]
      dense: [Facade, CITISUP, House, boxer]
      sparse: [EPFL, Unicorn, shiva, Arco]
    methods:
      - Main
      - G-PCC
      - V-PCC
      - IT-DL-PCC
      - JPEG-Pleno
  ablation_shepard:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      Main:
        label:
        color:
        markers:
      Ablation_Shepard:
        label:
        color:
        markers:
  ablation_fixed:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      Main:
        label:
        color:
        markers:
      Ablation_Fixed:
        label:
        color:
        markers:
  ablation_qfunc:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      Main:
        label:
        color:
        markers:
      Ablation_qFunc_Linear:
        label:
        color:
        markers:
      Ablation_qFunc_Exponential:
        label:
        color:
        markers: