# This defines the setup for plots
settings:
  groups: 
    8iVFB: [longdress, soldier, loot, redandblack]
    solid: [soldier, bouquet, stmichael, thaidancer]
    dense: [Facade, CITISUP, House, boxer]
    sparse: [EPFL, Unicorn, shiva, Arco]
  methods:
    - Main
    - G-PCC
    - V-PCC
    - IT-DL-PCC
    - JPEG-Pleno
    - DeepPCC
    - YOGA
    - Ablation_Shepard
    - Ablation_fixed
    - Ablation_lambdaFunc_linear
    - Ablation_lambdaFunc_exponential
    - Ablation_Inverse_nn

# This defines all the plots
plots:
  main_8i:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      - Main
      - G-PCC
      - V-PCC
      - IT-DL-PCC
      - DeepPCC
      - YOGA

  main_jpeg:
    groups: 
      solid: [soldier, bouquet, stmichael, thaidancer]
      dense: [Facade, CITISUP, House, boxer]
      sparse: [EPFL, Unicorn, shiva, Arco]
    methods:
      - Main
      - G-PCC
      - V-PCC
      - IT-DL-PCC
      - JPEG-Pleno

  Ablation_Shepard:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      - Main
      - Ablation_Shepard

  ablation_fixed:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      - Main
      - Ablation_fixed

  ablation_lambdaFunc:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      - Main
      - Ablation_lambdaFunc_linear
      - Ablation_lambdaFunc_exponential

  ablation_inverseScaling:
    groups: 
      8iVFB: [longdress, soldier, loot, redandblack]
    methods:
      - Main
      - Ablation_Inverse_nn