## General
experiment_name: "Debug"
results_path : "./results"

# Model
model:
  entropy_model: 
    type: "MeanScaleHyperprior" 
    C_bottleneck: 160
    C_hyper_bottleneck: 128
  g_a: 
    C_in: 4
    N1: 64
    N2: 128
    N3: 128
  g_s:
    C_out: 4
    N1: 128
    N2: 128
    N3: 64

## Data
data_path: "./data/datasets/full_128"
min_points_train: 100
min_points_test: 0
transforms:
  train:
    1_Rotate:
      key: "RandomRotate"
      block_size: 128
    2_Project:
      key: "ProjectTexture"
      block_size: 128
      dataset_dir: ./data/datasets
    3_Rotate:
      key: "RandomRotate"
      block_size: 128

## Training
device: "3"
epochs: 100
batch_size: 8
virtual_batches: false
model_learning_rate: 0.0001
bottleneck_learning_rate: 0.01
optimizer: "Adam"
scheduler_step_size: 30
scheduler_gamma: 0.5
clip_grad_norm: 1.0

## Loss:
loss:
  SSIM:
    type: "ColorSSIM"
    window_size: 5
    weight: 1.0
    loss: "L2"
  #L2:
    #type: "ColorLoss"
    #loss: "L2"
  bpp-y:
    type: "BPPLoss"
    key: "y"
    weight: 1.0
  bpp-z:
    type: "BPPLoss"
    key: "z"
    weight: 1.0