## General
experiment_name: "03_25_Debug_ColorsL2_2models_res_proj_256"
results_path : "./results"

# Model
model:
  entropy_model: 
    type: "MeanScaleHyperprior" 
    C_bottleneck: 128
    C_hyper_bottleneck: 128
  entropy_model_map: 
    type: "MeanScaleHyperprior" 
    C_bottleneck: 32
    C_hyper_bottleneck: 32
  g_a: 
    C_in: 4
    N1: 32
    N2: 128
    N3: 128
  g_s:
    C_out: 3
    N1: 128
    N2: 128
    N3: 32

## Data
data_path: "./data/datasets/full_256"
min_points_train: 300
min_points_test: 0
transforms:
  train:
    1_ColorJitter:
      key: "ColorJitter"
    2_Project:
      key: "ProjectTexture"
      block_size: 256
      dataset_dir: ./data/datasets
      probability: 0.5
    4_Rotate:
      key: "RandomRotate"
      block_size: 256

#Q_Map
q_map:
  lambda_A_min: 200
  lambda_A_max: 3200
  lambda_G_min: 50
  lambda_G_max: 400

## Training
device: "0"
epochs: 120
batch_size: 4
virtual_batches: false
model_learning_rate: 0.0001
bottleneck_learning_rate: 0.001
optimizer: "Adam"
scheduler_step_size: 60
scheduler_gamma: 0.5
clip_grad_norm: 1.0

## Loss:
loss:
  Multiscale_FocalLoss:
    type: "Multiscale_FocalLoss"
    alpha: 0.5
    gamma: 2.0
  ColorLoss:
    type: "ColorLoss"
    loss: "L2"
  bpp-y:
    type: "BPPLoss"
    key: "y"
    weight: 1.0
  bpp-z:
    type: "BPPLoss"
    key: "z"
    weight: 1.0